[env]
TERM= "screen-256color"

[terminal.shell]
program= "C:\\Program Files\\nu\\bin\\nu.exe"
args = []

[general]
import = [
	"everforest_dark.toml"
]

working_directory = "C:\\Users\\chr_58"

[window]

opacity = 1

padding.x = 0
padding.y = 0
dynamic_padding = true

title="~"
dynamic_title=true

decorations ="Full"
decorations_theme_variant = "Dark"

[font]

normal.family = "Cascadia Mono NF"
bold.family = "Cascadia Mono NF"
italic.family = "Cascadia Mono NF"
bold_italic.family = "Cascadia Mono NF"

size = 12.0

offset = { x = 0, y = 1 }

[cursor]
style = {shape="Block",blinking="Never"}
unfocused_hollow = true

[keyboard]

bindings = [
{ key="F11", action="ToggleFullscreen" },
{ key = "N", mods = "Control|Shift", action = "CreateNewWindow" },
{ key = "Space", mods="Control",action = "ToggleViMode" },
]

[colors]
# cursor = { text = "CellBackground" ,cursor = "#cb4b16" } #red
# cursor = { text = "CellBackground" ,cursor = "#51afef" } #blue
# cursor = { text = "CellBackground" ,cursor = "#00ff00"} #green
cursor = { text = "CellBackground" ,cursor = "#d3c6aa" } #everforest
